### ISSUE TITLE
Reaching invalid state by dispatching continuosly

### ISSUE THREAD

**Issue by shakdwipeea** [Day8/re-frame#469] opened 2018-05-22 10:10 UTC
I am trying to run re-frame on clojure. I am running into a invalid route when I dispatch continuosly.
The error msg I get is:
```
Exception in thread "pool-1-thread-1" clojure.lang.ExceptionInfo: re-frame: router state transition not found. :scheduled :finish-run {:fsm-state :scheduled, :trigger :finish-run}
```

I have created a repo to reproduce this:
https://github.com/shakdwipeea/reframe-state-transition-bug

**Comment by danielcompton** [comment] 2018-05-22 21:47
It looks like there may be a race condition here in the Clojure (note, not ClojureScript) code. I could reproduce this as well. After looking at the code for a few minutes, my best guess is that an event is dispatched while the executor is running and the FSM is in the `:running` state. The executor tries to run the `:finish-run` trigger, but underneath it, the FSM was moved back to the `:scheduled` state.

**Comment by danielcompton** [comment] 2018-05-29 02:35
Fixed in #471

**Closed by danielcompton** 2018-05-29 02:35 UTC
Labels: bug, help wanted

**Comment by piotr-yuxuan** [comment] 2018-08-23 08:47
That feeling when I've been stumbling upon a weird error for some hours, finally I get convinced that nothing obvious in my code is responsible for it, I find this issue which has exactly the same symptoms and at the end of it I can read « Fixed » ❤️

**Comment by piotr-yuxuan** [comment] 2018-08-23 08:51
@scgilardi and @danielcompton thanks a lot for your work in https://github.com/Day8/re-frame/pull/471. However, might I suggest you to release it? ^^ looks like it's currently in master, but latest release comes from February.
