### ISSUE TITLE
Docstrings for events?

### ISSUE THREAD

**Issue by JJ-Atkinson** [day8/re-frame#567] opened 2020-01-21 17:54 UTC
Could a docstring arg be included for `reg-event-db`, `reg-fx`, and `reg-sub`? Cursive supports the syntax so I can goto a `reg-fx` subscription, so it has enough semantic knowledge to pull out the doc string. I don't know about other editors.

**Comment by kimo-k** [comment] 2023-07-30 19:41
Duplicate of https://github.com/day8/re-frame/issues/457

Also see https://github.com/day8/re-frame/blob/master/docs/EPs/001-CaptureHandlerMetadata.md

**Closed by kimo-k** 2023-07-30 19:41 UTC
