### ISSUE TITLE
dispatch-n calling dispatch-n evaluates events in a non-obvious order

### ISSUE THREAD

**Issue by Folcon** [day8/re-frame#572] opened 2020-02-09 13:44 UTC
This is probably defined behaviour, but I just found this really surprising, I thought it was a bug until I eventually worked out what was going on. Now I'm just not sure.

```clojure
(rf/reg-event-fx
  ::pr
  (fn [_ [_ v]]
    (println :pr v)))

(rf/reg-event-fx
  ::first
  (fn [_ _]
    (println :called ::first)
    {:dispatch-n [[::pr 1] [::pr 2] [::pr 3]]}))

(rf/reg-event-fx
  ::second
  (fn [_ _]
    (println :called ::second)
    {:dispatch-n [[::first] [::pr 10] [::pr 20]]}))
```

Dispatching `::first`, then `::second`.

```clojure
:called :example.dev/first
:pr 1
:pr 2
:pr 3

:called :example.dev/second
:called :example.dev/first
:pr 10
:pr 20
:pr 1
:pr 2
:pr 3
```

I was expecting the output of dispatching `::second` to be:
```clojure
:called :example.dev/first
:pr 1
:pr 2
:pr 3

:called :example.dev/second
:called :example.dev/first
:pr 1
:pr 2
:pr 3
:pr 10
:pr 20
```

I suppose this is why `:dispatch-later` exists?

**Comment by Folcon** [comment] 2020-02-09 13:52
Ok, so a few minutes of thinking made me realise `:dispatch-later` was a terrible way to solve this.

Wrote ::defer instead:
```clojure
(rf/reg-event-fx
  ::defer
  (fn [_ [_ {:keys [dispatch dispatch-n]}]]
    (merge
      (when dispatch   {:dispatch   dispatch})
      (when dispatch-n {:dispatch-n dispatch-n}))))
```

Is there a more elegant solution?

**Comment by jrad87** [comment] 2020-03-30 00:44
Dispatching events places them into queue which probably processes events in a roughly first-in first-out manner so look at it step by step
1. ::second is dispatched.
2. Now the first element in the queue is ::second, and when it is processed, it will place [::first] [::pr 10] and [::pr 20] at the end of the queue in that order.
3. Now the first element in the queue is ::first. After processing it will place [::pr 1] [::pr 2] and [::pr 3] at the end of the queue in that order. [::pr 10] and  [::pr 20] are still in the queue and still await processing. The current state of the queue is then [::pr 10] [::pr 20] [::pr 1] [::pr 2] [::pr 3]. And these events are processed in the order you have already seen.

Is there a reason you couldn't do
```
(reg-event-fx 
  ::first 
    (fn [_ _] 
      {:dispatch-n [[::pr 1] [::pr 2] [::pr 3] [::second]]})

(reg-event-fx 
  ::second 
    (fn [_ _] 
      {:dispatch-n [[::pr 10] [::pr 20]]}
```

**Comment by Folcon** [comment] 2020-03-30 11:59
Oh, that's because the way I designed it `::first` is supposed to be independent of `::second` as first would be something like say file upload and `::second` is a workflow to be run on the uploaded file. It defeats the purpose of having `::first` be a relatively general purpose file upload event that can be reused if I have to create multiple custom versions which each refer to a separate `::second`.

**Comment by superstructor** [comment] 2020-05-04 05:12
There doesn't appear to be an issue here.  This is all expected behaviour because re-frame events are handled via a FIFO queue. 
To obtain support please see the suggestions in [`/Support.md`](https://github.com/day8/re-frame/blob/master/SUPPORT.md) within this repo.
 
Closing

**Closed by superstructor** 2020-05-04 05:12 UTC
