### ISSUE TITLE
addEventListener and attachEvent unavailable when using with react-native 

### ISSUE THREAD

**Issue by zendevil** [day8/re-frame#621] opened 2020-06-30 16:11 UTC
I'm using the re-frame library in a react-native project, and including it gives the following error:
<img width="364" alt="Screen Shot 2020-06-30 at 9 11 22 AM" src="https://user-images.githubusercontent.com/30054030/86150024-aba64600-bab1-11ea-97b0-45309679d8eb.png">

This error seems to be about web-specific functions that aren't available in native. How to fix this error?

**Comment by superstructor** [comment] 2020-07-01 02:48
Thanks for the report. This is a duplicate of #604 so will close this and continue tracking it there.

**Closed by superstructor** 2020-07-01 02:48 UTC
