### ISSUE TITLE
Re-frame hangs in Safari 9.1

### ISSUE THREAD

**Issue by StephenCharles** [Day8/re-frame#146] opened 2016-01-18 23:24 UTC
I recently upgraded re-frame from `0.4.1` to `0.6.0` and it worked great in chrome and firefox but would just hang when dispatching in Safari 9.1. I also tried both `0.5.0` and `0.7.0-alpha` which resulted in the same hanging behavior in Safari.

on page load, this is dispatched:
```
;; core.cljs
(dispatch [:initialize-db])
----------------------------------
;; handlers.cljs
;; GET is from the cljs-ajax library
(defn initialize-db [db _]
  (GET "/init"
    {:handler #(dispatch [:process-initialize-db %1])
     :error-handler #(dispatch [:error-initialize-db %1])}) db)
```
Safari would show the `init` xhr request in the network tab but would just hang; continuously loading. No js errors or warnings were thrown. Also, my server was never hit with the `init` GET request. 

Other dependencies in my project:
```
     [org.clojure/clojure "1.8.0-RC1"]
     [org.clojure/clojurescript "1.7.170"]
     [org.clojure/core.async "0.2.374"]
     [org.clojure/test.check "0.9.0"]
     [secretary "1.2.3"]
     [reagent "0.5.1"]
     [cljs-ajax "0.5.3"]
     [prismatic/dommy "1.1.0"]
     [prismatic/schema "1.0.4"]
     [com.cognitect/transit-cljs "0.8.237"]
     [org.clojars.stephen-charles/re-com "0.5.7"]]
   :plugins [[lein-cljsbuild "1.1.2"]
            [lein-ancient "0.6.8"]
            [lein-figwheel "0.5.0-2"]]
```

**Comment by danielcompton** [comment] 2016-01-19 07:21
Hi @StephenCharles, can you reproduce this issue with the example re-frame project? It kinda looks like an issue with the XHR request, not re-frame?

**Comment by StephenCharles** [comment] 2016-01-19 17:23
I'll look into it. May take a bit of time as I have to annoy some friends to test it in Safari for me.

**Comment by danielcompton** [comment] 2016-01-19 19:15
FWIW, I've done a fair amount of work with re-frame in Safari. I vaguely remember some bugs that were timing related that didn't show up in Chrome. The gist of it was that I was trying to call handlers that hadn't been created yet because I was evaluating forms in the namespace directly, rather than calling functions once I knew the handlers were set up. Not sure if that applies to you here, but maybe experiment with calling `(dispatch [:initialize-db])` after the page is loaded just to start tracking down the source of the problem?

**Comment by StephenCharles** [comment] 2016-01-19 19:15
Just tested the example app and it works fine with `cljs-ajax` in Safari.

This error was reproduce-able in my original application (by changing the re-frame version) but my application has a lot more dependencies and external javascripts. See dependencies above and below are the external javascripts:

```
/* v 1.0.2 */ Chart.min.js  
/* v 2.10.3 */ moment.min.js
/* v 1.4.4 */ rollbar.min.js
/* v 1.1.1 */ faye.js
/* v 15-01-2016 */ https://js.stripe.com/v2/
/* v 1.11.2 */ jquery
/* v 2135554 */ https://connect.facebook.net/en_US/fbevents.js
/* v 4.0.3 of the jquery-rails ruby gem*/
https://github.com/rails/jquery-rails/blob/ff93f91b279a760472e459e8e4ad6cdf1cc5bcf4/vendor/assets/javascripts/jquery_ujs.js
```

I'll close this issue for now until I can better understand what is happening. I also wanted to see if this was happening to anyone else. Otherwise it may just be an application error on my end.

**Comment by danielcompton** [comment] 2016-01-19 19:20
Sorry, I didn't read your first report carefully enough, which versions of re-frame does your app work and not work with when using Safari?

**Comment by StephenCharles** [comment] 2016-01-19 19:23
It works with `0.4.1` and below. `0.5.0`, `0.6.0`, and `0.7.0-alpha` do not work. 

Were these timing errors occurring before `0.5.0`? And what exactly would happen?

**Comment by mike-thompson-day8** [comment] 2016-01-19 19:41
In v0.5, we re-implemented the router loop (the code that queues and processes events when they have been `dispatch`ed), dropping the previous loop which was based on `core.async`: 
https://github.com/Day8/re-frame/blob/master/CHANGES.md#050--2015-11-5

One implication of the new router loop is that there's less of a delay between when a `dispatch` happens and when the associated event-handlers is run.  Prior to v0.5 there would have been at least a 5ms delay (from dispatch to event-handler), but with 0.5 that might shrink to < 1ms.

**Comment by StephenCharles** [comment] 2016-01-19 20:11
OO interesting. Well maybe other event-handlers are being processed as well? 

here is the full context of what is being run on page load:
```
;; core.cljs
(defn ^:export main
   (re-frame/dispatch [:initialize-db])
   ;; this method will dispatch a handler for a given pathname
   (secretary/dispatch! (.-location.pathname js/window)))

--------------------------------------------
;; handlers.cljs
;; as far as I can tell, it never makes it to process-initialize-db or error-initialize-db because
;; the GET request never finishes
(defn initialize-db [db _]
  (GET "/init"
    {:handler #(dispatch [:process-initialize-db %1])
     :error-handler #(dispatch [:error-initialize-db %1])}) db)

;;; an example of a handler for a given pathname
;;; that would be dispatched from secretary/dispatch!
(defn view-dashboard-activity [db _]                                                               
  (let [dashboard (get-in db [:data :dashboard])]                                                  
    (when (nil? dashboard)                                                                         
      (dispatch [:all-dashboard-loading true])  ;; this handler just updates a key in the db                                                
      (dispatch [:initialize-dashboard])) ;; this will make a GET request similar to initialize-db (which is never made according to the Safari network tab)                                                         
    (assoc-in db [:view :current-route] r/dashboard-activity-route)))
```

I'm sorry I can't provide more information. Currently the only access I have to Safari is through a friend who lives 3000 miles away. In a week or so I'll be able to explore this more thoroughly.

**Comment by mike-thompson-day8** [comment] 2016-01-19 20:42
I half suspect you've got a race-condition somewhere. The previous router masked the problem because it processed events much more slowly (more time in between event handlers getting called).  

Having said that, I'm not sure why it would only happen on Safari OR why it would manifest as a weird hang. 

As an experiment, what happens if  you cheat and use `(re-frame/dispatch-sync [:initialize-db])`?

Ultimately, I suspect you'll have to debug via this kind of method, to "see" what is happening:
https://github.com/Day8/re-frame/wiki/Debugging

**Comment by mike-thompson-day8** [comment] 2016-01-28 12:16
@StephenCharles I was wondering if you got to the bottom of this?   We okay to close this?

**Comment by StephenCharles** [comment] 2016-01-28 17:32
I haven't had a chance to do any further debugging. At the moment I don't have easy access to a machine with Safari on it. I'm hoping to borrow someone's machine in a week or so.

**Comment by jhund** [comment] 2016-02-02 17:02
@StephenCharles it appears that you connect your re-frame app to a Rails backend. Is that correct? If so, could we talk about how you do it? I'm in the process of developing a Ruby Gem that makes connecting re-frame and Rails easier: https://github.com/jhund/re-frame-on-rails

**Comment by jhund** [comment] 2016-02-02 17:03
@StephenCharles by the way, I'm on Mac OS and could help with testing on Safari.

**Comment by StephenCharles** [comment] 2016-02-02 22:51
After looking over the wiki about best practices, I realized I was using subscriptions in many of my handlers. I'm not sure if this will fix the problem, but it is worth a shot.

@jhund yeah I use re-frame with rails, I'll open an issue on your repo and we can chat about it there. Thanks for the offer but it's looking like this is probably specific to my application and so I'll be bugging my co-worker about debugging it with me.

**Comment by StephenCharles** [comment] 2016-02-04 21:51
Ok it seems it was an application on my part. I removed all the subscriptions from my handlers, and newest re-frame `0.7.0-alpha-2` works great in Safari 9.1 and 9.0.3. I'll be sure to familiarize myself with the wiki more often :)

**Closed** 2016-02-06 19:27 UTC
